import { z } from 'zod'
const text=z.string().min(1).max(500),id=z.string().min(1).max(256),integer=z.number().int().nonnegative()
const attrs=z.object({attack:z.number().finite(),defense:z.number().finite(),physical:z.number().finite(),mental:z.number().finite()}).strict()
const unit=z.number().int().min(0).max(1)
const delta=z.object({goals:unit,assists:unit,yellowCards:unit,redCards:z.literal(0),averageRating:z.number().finite().min(-.15).max(.15)}).strict().refine(x=>x.goals+x.assists<=1)
const applied=z.object({goals:unit,assists:unit,yellowCards:unit,redCards:z.literal(0),averageRating:z.number().finite().min(-3).max(3)}).strict().refine(x=>x.goals+x.assists<=1)
const outcome=z.object({text,delta}).strict()
const choice=z.object({id,title:text,explanation:text,risk:z.enum(['LOW','MEDIUM','HIGH']),weights:attrs.refine(a=>Object.values(a).every(v=>v>=0)&&Math.abs(Object.values(a).reduce((s,v)=>s+v,0)-1)<=.001),difficulty:z.number().finite().min(0).max(100),outcomes:z.object({EXCELLENT:outcome,POSITIVE:outcome,NEGATIVE:outcome}).strict()}).strict()
const identity={id,windowIndex:integer,clubId:id,templateId:id,templateRevision:z.number().int().positive(),rulesVersion:z.literal(1),minute:z.number().int().min(1).max(90),ownScore:z.number().int().min(0).max(9),opponentScore:z.number().int().min(0).max(9),debutMoment:z.boolean(),title:text,scene:text}
const resolution=z.object({momentId:id,windowIndex:integer,clubId:id,templateId:id,choiceId:id,tier:z.enum(['EXCELLENT','POSITIVE','NEGATIVE']),text,delta}).strict()
export const momentSnapshotSchema=z.object({...identity,choiceTitle:text,result:resolution,appliedStatsDelta:applied}).strict().refine(x=>x.id===x.result.momentId&&x.windowIndex===x.result.windowIndex&&x.clubId===x.result.clubId&&x.templateId===x.result.templateId&&x.appliedStatsDelta.goals===x.result.delta.goals&&x.appliedStatsDelta.assists===x.result.delta.assists&&x.appliedStatsDelta.yellowCards===x.result.delta.yellowCards)
export const pendingMomentSchema=z.object({...identity,fingerprintVersion:z.literal(1),inputFingerprint:z.string().regex(/^[0-9a-f]{16}$/),choices:z.array(choice).length(3).refine(cs=>new Set(cs.map(c=>c.id)).size===3),prepared:z.object({attributes:attrs,form:z.number().finite().min(0).max(100),fitness:z.number().finite().min(0).max(100),morale:z.number().finite().min(0).max(100),actualTeamLevel:z.literal('FIRST_TEAM')}).strict(),baseStats:z.object({appearances:integer,starts:integer,minutes:integer,goals:integer,assists:integer,yellowCards:integer,redCards:integer,averageRating:z.number().finite().min(5.5).max(8.5)}).strict(),roll:z.number().finite().min(0).lt(1),selectedChoiceId:id.nullable(),resolution:resolution.nullable(),snapshot:momentSnapshotSchema.nullable()}).strict()
