import { it, expect, vi } from 'vitest'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { gzipSync, gunzipSync } from 'node:zlib'
import { createTrainingBaselineState } from '../../../../src/engine/__tests__/ceuTrainingBaselineFixture'
import { simulateProfessionalHalfYear } from '../../../../src/engine/simulateProfessionalHalfYear'
import * as training from '../../../../src/engine/trainingPlan'
import { saveGame, loadGame } from '../../../../src/persistence/save'
import { useGameStore } from '../../../../src/store/gameStore'
import { SAVE_VERSION, DATA_VERSION, type GameState } from '../../../../src/models/game'
const D='docs/evidence/PSU-20260912/S2', collect=process.env.PSU_S2_COLLECT==='1', sha=(b:any)=>createHash('sha256').update(b).digest('hex')
const put=(name:string,data:any)=>{if(!collect)return;writeFileSync(`${D}/${name}`,JSON.stringify(data,null,2),{flag:'wx'})}
function storage(){const m=new Map<string,string>();vi.stubGlobal('window',{localStorage:{getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>m.set(k,v),removeItem:(k:string)=>m.delete(k),clear:()=>m.clear()}});return m}
const approaches=['PUSH','STEADY','TEAM_FIRST'] as const,roles=['FRINGE','SUBSTITUTE','ROTATION','STARTER','CORE'] as const
function diff(a:any,b:any,path=''):any[]{if(JSON.stringify(a)===JSON.stringify(b))return [];if(a&&b&&typeof a==='object'&&typeof b==='object')return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>diff(a[k],b[k],path+'/'+k));return [{path,before:a,after:b}]}
it('freezes paired current-engine matrix and finite boundary evidence; normal rerun read-only',()=>{
 expect([SAVE_VERSION,DATA_VERSION]).toEqual([12,12]);const before=JSON.parse(readFileSync(`${D}/before.json`,'utf8'));for(const [p,h] of Object.entries(before.files))if((String(p).startsWith('src/')&&!String(p).includes('__tests__')&&!String(p).endsWith('.test.ts')&&p!=='src/engine/simulateProfessionalHalfYear.ts')||p==='package.json'||p==='package-lock.json')expect(sha(readFileSync(p))).toBe(h)
 if(collect)expect(existsSync(`${D}/outputs.json.gz`)).toBe(false)
 let fixture:any
 if(existsSync(`docs/evidence/PSU-20260912/S1/inputs-valid.json`))fixture=JSON.parse(readFileSync(`docs/evidence/PSU-20260912/S1/inputs-valid.json`,'utf8'))
 else {expect(collect).toBe(true);const original=createTrainingBaselineState('psu-s1-source');const s=structuredClone(original.state);s.windowIndex=22;s.arrivalChoice='COACH';s.firstTeamRole='ROTATION';s.player!.name='PSU匿名基线';s.draft.name='PSU匿名基线';s.player!.attributes={attack:65,defense:65,physical:65,mental:65};s.player!.potentials={attack:90,defense:90,physical:90,mental:90};for(const k of ['form','fitness','morale'] as const)s.player![k]=70;for(const k of ['coachRelation','squadRelation','agentRelation','fanRelation','mediaRelation','clubAttachment'] as const)s.player![k]=60;s.contract!.remainingHalfYears=8;s.contract!.promisedTeamLevel='FIRST_TEAM';s.contract!.promisedRole='ROTATION';fixture={kind:'constructed, generated once, paired strategy comparisons never regenerate player',generatorSeed:'psu-s1-source',original,base:{state:s,academy:original.academy},changes:diff(original.state,s),mainSeeds:Array.from({length:100},(_,i)=>`psu-main-${String(i).padStart(3,'0')}`),injurySeedsForS2:Array.from({length:1000},(_,i)=>`psu-injury-${String(i).padStart(4,'0')}`)};put('inputs-valid.json',fixture)}
 const base=fixture.base.state as GameState,offer=fixture.base.academy;let captured:any
 const orig=training.applyTrainingMaintenance;const spy=vi.spyOn(training,'applyTrainingMaintenance').mockImplementation((...args)=>{const execution=orig(...args);captured={prepared:structuredClone(args[1]),execution:structuredClone(execution)};return execution})
 const outputs:any[]=[];function run(id:string,s:GameState,group:string){const frozen=JSON.stringify(s);const m=storage();saveGame(s);const raw=m.get('career_save_current')!;const loaded=loadGame()!;const loadChanges=diff(s,loaded);const input=structuredClone(loaded);const o=simulateProfessionalHalfYear({state:input,offer});const probe=structuredClone(captured);expect(JSON.stringify(input)).toBe(JSON.stringify(loaded));const repeat=simulateProfessionalHalfYear({state:structuredClone(loaded),offer});expect(repeat).toEqual(o);if(loaded.developmentApproach===null)expect(simulateProfessionalHalfYear({state:{...structuredClone(loaded),developmentApproach:'STEADY'},offer})).toEqual(o);expect(JSON.stringify(s)).toBe(frozen);expect(o.report.stats.starts).toBeGreaterThanOrEqual(0);expect(o.report.stats.starts).toBeLessThanOrEqual(o.report.stats.appearances);expect(o.report.stats.appearances).toBeLessThanOrEqual(18);expect(o.report.stats.minutes).toBeGreaterThanOrEqual(0);const risk=Math.min(.12,Math.max(.03,.04+(50-probe.prepared.fitness)*.001+(45-probe.prepared.attributes.physical)*.0005));outputs.push({id,group,seed:s.careerSeed,inputChanges:diff(base,s),loadedChanges:loadChanges,inputSHA:sha(JSON.stringify(s)),rawSHA:sha(raw),actualTeam:o.report.contract?.actualTeamLevel,probe,oldRiskFormulaForComparison:o.report.contract?.actualTeamLevel==='FIRST_TEAM'?risk:null,output:o});return o}
 for(const role of roles)for(const approach of approaches)for(const seed of fixture.mainSeeds){const s=structuredClone(base);s.careerSeed=seed;s.firstTeamRole=role;s.contract!.promisedRole=role;s.developmentApproach=approach;run(`${role}/${approach}/${seed}`,s,'main')}
 const cases:any[]=[];function add(id:string,mut:(s:GameState)=>void,aa:readonly any[]=approaches){for(const a of aa){const s=structuredClone(base);s.careerSeed='psu-boundary-000';s.firstTeamRole='FRINGE';s.contract!.promisedRole='FRINGE';s.developmentApproach=a;mut(s);cases.push({id:`${id}/${a}`,state:s})}}
 for(const k of ['form','fitness','morale'] as const)for(const value of [45,46,47])add(`${k}-${value}`,s=>{s.player![k]=value})
 for(const age of [30,31,34])add(`age-${age}`,s=>{s.windowIndex=(age-13)*2;s.trainingFocus=age===30?'BALANCED':'BODY_CARE'})
 for(const value of [95,100])for(const focus of ['BODY_CARE','MATCH_SHARPNESS','MENTAL_RESET'] as const)add(`high-${value}-${focus}`,s=>{s.windowIndex=42;s.trainingFocus=focus;s.player!.form=s.player!.fitness=s.player!.morale=value})
 for(const value of [70,45])add(`null-${value}`,s=>{s.player!.form=value},[null])
 for(const age of [21,22])add(`youth-${age}`,s=>{s.windowIndex=(age-13)*2;s.teamLevel='YOUTH';s.firstTeamRole=null;s.youthRole='ROTATION';s.contract!.promisedTeamLevel='YOUTH';s.contract!.promisedRole='ROTATION';s.arrivalChoice='COACH'})
 expect(cases).toHaveLength(62);for(const c of cases)run(c.id,c.state,'boundary')
 const defect=outputs.filter(r=>r.group==='boundary'&&/^form-45\//.test(r.id));const a=defect.find(r=>r.id.endsWith('TEAM_FIRST')),b=defect.find(r=>r.id.endsWith('STEADY'));expect(a.probe.execution).toBeNull();expect(a.probe.prepared.squadRelation).toBe(60);expect(a.output.report.stats).toEqual(b.output.report.stats);expect(a.output.player.squadRelation-b.output.player.squadRelation).toBe(0);put('recovery-fixed.json',{knownDefect:false,note:'S1 defect fixed with explicit recovery; old input preserved; all three recovery outputs agree',teamFirst:a,steady:b,differences:diff(b.output,a.output)})
 const storeRows=[];for(const s0 of [base,cases.find(c=>c.id==='form-45/TEAM_FIRST').state,cases.find(c=>c.id==='age-34/STEADY').state]){const s=structuredClone(s0),m=storage();saveGame(s);useGameStore.setState({game:null,error:null,hasSave:true});useGameStore.getState().continueCareer();const after=structuredClone(useGameStore.getState().game);expect(useGameStore.getState().error).toBeNull();expect(after!.phase).toBe('HALF_YEAR_REPORT');expect(after!.history).toHaveLength(s.history.length+1);const raw=m.get('career_save_current');useGameStore.getState().continueCareer();expect(useGameStore.getState().game).toEqual(after);expect(m.get('career_save_current')).toBe(raw);storeRows.push({input:s,after,finalRaw:raw})}put('store-successors.json',storeRows)
 spy.mockRestore();vi.unstubAllGlobals();if(collect)writeFileSync(`${D}/outputs.json.gz`,gzipSync(JSON.stringify(outputs)),{flag:'wx'});else expect(outputs).toEqual(JSON.parse(gunzipSync(readFileSync(`${D}/outputs.json.gz`)).toString()));put('run-summary.json',{main:1500,boundary:62,uniqueEngineInputs:1562,determinismRepeats:1562,storeSuccessors:3,sourceSHA:sha(readFileSync(`docs/evidence/PSU-20260912/S1/inputs-valid.json`)),outputSHA:sha(collect?readFileSync(`${D}/outputs.json.gz`):Buffer.from(''))});
})
